version: '3.3'
services:
  db:
    image: postgres:14.2-alpine
    #command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=32505856
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5434:5432
    volumes:
      - ./database/base.sql:/docker-entrypoint-initdb.d/base.sql
      - mileapp_local_db:/var/lib/postgresql/data
    networks:
      - mileapp_screening

  mongo:
    image: mongo:7.0-jammy
    restart: always
    volumes:
      - mileapp_db_mongo:/data/db
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mileapp_screening

  app:
    build: .
    ports:
      - 5000:5000
    restart: on-failure
    env_file: ./.env
    volumes:
      - ./:/app
    depends_on:
      - db
      - mongo
    networks:
      - mileapp_screening

networks:
  mileapp_screening:
volumes:
  mileapp_local_db:
  mileapp_db_mongo:
